apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/cert-manager-issuers
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: cert-manager-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
