apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/metallb-config
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: metallb-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
